export const GET_LASTCARTOON = 'GET_LASTCARTOON';
export const SET_LASTCARTOON = 'SET_LASTCARTOON';
export const SET_DISPLAYEDCARTOON = 'SET_DISPLAYEDCARTOON';
export const DISPLAY_PREVIOUS_CARTOON = 'DISPLAY_PREVIOUS_CARTOON';
export const DISPLAY_NEXT_CARTOON = 'DISPLAY_NEXT_CARTOON';
