export const GET_LASTCARTOON = 'GET_LASTCARTOON';
export const SET_LASTCARTOON = 'SET_LASTCARTOON';
export const SET_CURRENT_DISPLAYED_CARTOONS = 'SET_CURRENT_DISPLAYED_CARTOONS';
export const DISPLAY_PREVIOUS_CARTOON = 'DISPLAY_PREVIOUS_CARTOON';
export const DISPLAY_NEXT_CARTOON = 'DISPLAY_NEXT_CARTOON';
